const $=s=>document.querySelector(s),keys=new Set(),params=new URLSearchParams(location.search),popupMode=params.get("popup")==="1";let active="menu",miniGame=params.get("game")||"maze",installPrompt=null;
// The versioned script URL prevents old builds; this worker never stores game files.
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"}));
addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e});
function openGame(id){active=id;$("#menu").style.display="none";document.querySelectorAll(".play").forEach(x=>x.style.display=x.id===id?"block":"none");document.querySelectorAll(".home").forEach(x=>x.style.display="block");}
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openGame(b.dataset.open));document.querySelectorAll(".home").forEach(b=>b.onclick=()=>{active="menu";$("#menu").style.display="block";document.querySelectorAll(".play").forEach(x=>x.style.display="none")});
// Maze: recursive backtracker creates a fresh connected maze every run.
let mazeDifficulty=params.get("difficulty")||"medium",mz={cols:15,rows:10,cells:[],x:0,y:0,level:1,start:0,playing:false};
function makeMaze(level=mz.level){let base={easy:[9,6],medium:[15,10],hard:[23,15]}[mazeDifficulty],cols=Math.min(35,base[0]+Math.floor((level-1)/2)*2),rows=Math.min(23,base[1]+Math.floor((level-1)/3));if(cols%2===0)cols++;if(rows%2===0)rows++;let cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({v:0,w:[1,1,1,1]}))),stack=[[0,0]];cells[0][0].v=1;while(stack.length){let [x,y]=stack[stack.length-1],opts=[];[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]].forEach(([dx,dy,a,b])=>{let nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<cols&&ny<rows&&!cells[ny][nx].v)opts.push([nx,ny,a,b])});if(!opts.length){stack.pop();continue}let [nx,ny,a,b]=opts[Math.floor(Math.random()*opts.length)];cells[y][x].w[a]=0;cells[ny][nx].w[b]=0;cells[ny][nx].v=1;stack.push([nx,ny])}mz={cols,rows,cells,x:0,y:0,level,start:performance.now(),playing:true};$("#mazeCover").hidden=true;drawMaze()}
function mazeMove(d){if(!mz.playing)return;let dirs={up:[0,-1,0],right:[1,0,1],down:[0,1,2],left:[-1,0,3]},[dx,dy,w]=dirs[d];if(!mz.cells[mz.y][mz.x].w[w]){mz.x+=dx;mz.y+=dy;drawMaze();if(mz.x===mz.cols-1&&mz.y===mz.rows-1){mz.playing=false;mz.level++;$("#mazeTitle").textContent=`탈출 성공! 다음은 LEVEL ${mz.level}`;$("#mazeStart").textContent="더 큰 새 미로";if(popupMode){$("#miniTitle").textContent=`탈출! LEVEL ${mz.level} 준비`;setTimeout(()=>{makeMaze(mz.level);$("#miniTitle").textContent=`미로 탈출 · LEVEL ${mz.level}`},700)}else $("#mazeCover").hidden=false}}}
function drawExcelGrid(x,w,h){x.fillStyle="#fff";x.fillRect(0,0,w,h);x.strokeStyle="#d9e0db";x.lineWidth=1;x.beginPath();for(let px=0;px<=w;px+=48){x.moveTo(px,0);x.lineTo(px,h)}for(let py=0;py<=h;py+=32){x.moveTo(0,py);x.lineTo(w,py)}x.stroke();x.fillStyle="#f2f4f3";x.fillRect(0,0,w,28);x.fillRect(0,0,32,h);x.strokeStyle="#b8c4bc";x.beginPath();x.moveTo(0,28);x.lineTo(w,28);x.moveTo(32,0);x.lineTo(32,h);x.stroke()}
function paintMaze(c){let x=c.getContext("2d"),cw=c.width/mz.cols,ch=c.height/mz.rows;drawExcelGrid(x,c.width,c.height);x.strokeStyle="#217346";x.lineWidth=Math.max(2,Math.min(cw,ch)*.1);x.beginPath();for(let y=0;y<mz.rows;y++)for(let q=0;q<mz.cols;q++){let a=mz.cells[y][q],px=q*cw,py=y*ch;if(a.w[0]){x.moveTo(px,py);x.lineTo(px+cw,py)}if(a.w[1]){x.moveTo(px+cw,py);x.lineTo(px+cw,py+ch)}if(a.w[2]){x.moveTo(px,py+ch);x.lineTo(px+cw,py+ch)}if(a.w[3]){x.moveTo(px,py);x.lineTo(px,py+ch)}}x.stroke();x.fillStyle="#c6e0b4";x.fillRect((mz.cols-1)*cw+cw*.18,(mz.rows-1)*ch+ch*.18,cw*.64,ch*.64);x.fillStyle="#217346";x.beginPath();x.arc(mz.x*cw+cw/2,mz.y*ch+ch/2,Math.min(cw,ch)*.28,0,Math.PI*2);x.fill()}
function drawMaze(){paintMaze($("#mazeCanvas"));$("#mazeLevel").textContent=`LEVEL ${mz.level}`}
$("#mazeStart").onclick=()=>makeMaze(mz.level);document.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>mazeMove(b.dataset.m));document.querySelectorAll("[data-md]").forEach(b=>b.onclick=()=>{mazeDifficulty=b.dataset.md;mz.level=1;document.querySelectorAll("[data-md]").forEach(x=>x.classList.toggle("active",x===b))});
// Sudoku: generate a valid shuffled solution and remove cells by difficulty.
let sudokuDifficulty="medium",sudokuSolution=[];
const shuffled=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function countSudokuSolutions(board,limit=2){let best=-1,candidates=null;for(let i=0;i<81;i++){if(board[i])continue;let used=new Set();let row=Math.floor(i/9),col=i%9;for(let k=0;k<9;k++){used.add(board[row*9+k]);used.add(board[k*9+col])}let br=Math.floor(row/3)*3,bc=Math.floor(col/3)*3;for(let y=0;y<3;y++)for(let x=0;x<3;x++)used.add(board[(br+y)*9+bc+x]);let opts=[];for(let n=1;n<=9;n++)if(!used.has(n))opts.push(n);if(!opts.length)return 0;if(!candidates||opts.length<candidates.length){best=i;candidates=opts;if(opts.length===1)break}}if(best<0)return 1;let total=0;for(const n of candidates){board[best]=n;total+=countSudokuSolutions(board,limit-total);board[best]=0;if(total>=limit)return total}return total}
function newSudoku(){let nums=shuffled([1,2,3,4,5,6,7,8,9]),bands=shuffled([0,1,2]),rows=bands.flatMap(b=>shuffled([0,1,2]).map(r=>b*3+r)),stacks=shuffled([0,1,2]),cols=stacks.flatMap(b=>shuffled([0,1,2]).map(c=>b*3+c));sudokuSolution=rows.flatMap(r=>cols.map(c=>nums[(r*3+Math.floor(r/3)+c)%9]));let target={easy:34,medium:45,hard:50}[sudokuDifficulty],puzzle=[...sudokuSolution],hidden=new Set();for(const i of shuffled([...Array(81).keys()])){if(hidden.size>=target)break;let old=puzzle[i];puzzle[i]=0;if(countSudokuSolutions(puzzle)===1)hidden.add(i);else puzzle[i]=old}let grid=$("#sudokuGrid");grid.innerHTML="";sudokuSolution.forEach((n,i)=>{let input=document.createElement("input");input.className="sudokuCell"+(hidden.has(i)?"":" given");input.inputMode="numeric";input.maxLength=1;input.dataset.index=i;input.setAttribute("aria-label",`${Math.floor(i/9)+1}행 ${i%9+1}열`);if(hidden.has(i)){input.oninput=()=>{input.value=input.value.replace(/[^1-9]/g,"").slice(0,1);input.classList.remove("bad")}}else{input.value=n;input.readOnly=true}grid.appendChild(input)});$("#sudokuMsg").textContent=`빈칸 ${hidden.size}개 · 정답은 하나뿐입니다.`;renderMiniSudoku()}
function renderMiniSudoku(){let box=$("#miniSudoku");if(!box)return;box.innerHTML="";document.querySelectorAll(".sudokuCell").forEach((source,i)=>{let input=document.createElement("input");input.className=source.classList.contains("given")?"given":"";input.inputMode="numeric";input.maxLength=1;input.value=source.value;if(source.readOnly)input.readOnly=true;else input.oninput=()=>{input.value=input.value.replace(/[^1-9]/g,"").slice(0,1);source.value=input.value;source.classList.remove("bad")};box.appendChild(input)})}
function checkSudoku(){let cells=[...document.querySelectorAll(".sudokuCell")],empty=false,wrong=false;cells.forEach((c,i)=>{if(!c.value)empty=true;let bad=c.value&&+c.value!==sudokuSolution[i];c.classList.toggle("bad",bad);if(bad)wrong=true});$("#sudokuMsg").textContent=wrong?"빨간 칸을 다시 확인하세요.":empty?"아직 빈칸이 남았습니다.":"정답입니다! 퍼즐을 완성했습니다."}
$("#sudokuNew").onclick=newSudoku;$("#sudokuCheck").onclick=checkSudoku;document.querySelectorAll("[data-sd]").forEach(b=>b.onclick=()=>{sudokuDifficulty=b.dataset.sd;document.querySelectorAll("[data-sd]").forEach(x=>x.classList.toggle("active",x===b));$("#sudokuMode").textContent={easy:"초급",medium:"중급",hard:"고급"}[sudokuDifficulty];newSudoku()});newSudoku();
// Dodge Fist.
let fs,rocks=[],fightKeys=new Set();const FC=$("#fightCanvas"),FX=FC.getContext("2d");
function startFight(){fs={p:{x:140,y:420,vy:0,hp:100,atk:0,inv:0},e:{x:770,hp:100,hit:0},score:0,t:0,spawn:0,on:true};rocks=[];$("#fightCover").hidden=true}
function fact(k,on){on?fightKeys.add(k):fightKeys.delete(k);if(!fs)return;if(on&&k==="attack")fs.p.atk=12;if(on&&k==="jump"&&fs.p.y>=419){fs.p.vy=-12.5}if(on&&k==="dodge"&&fs.p.inv<=0){fs.p.inv=28;fs.p.x+=fs.p.x<fs.e.x?-55:55}}
$("#fightStart").onclick=startFight;document.querySelectorAll("[data-f]").forEach(b=>{b.onpointerdown=()=>fact(b.dataset.f,true);b.onpointerup=b.onpointerleave=()=>fact(b.dataset.f,false)});
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function fightUpdate(dt){if(!fs||!fs.on)return;let p=fs.p,e=fs.e;fs.t+=dt;fs.spawn-=dt;if(fightKeys.has("left"))p.x-=5.3*dt;if(fightKeys.has("right"))p.x+=5.3*dt;p.x=Math.max(20,Math.min(902,p.x));p.vy+=.72*dt;p.y+=p.vy*dt;if(p.y>=420){p.y=420;p.vy=0}p.atk=Math.max(0,p.atk-dt);p.inv=Math.max(0,p.inv-dt);e.hit=Math.max(0,e.hit-dt);e.x+=Math.sign(p.x-e.x)*Math.min(2.2,Math.abs(p.x-e.x))*dt;if(p.atk>6&&overlap({x:p.x+(p.x<e.x?38:-42),y:p.y+18,w:42,h:22},{x:e.x,y:410,w:48,h:72})&&e.hit<=0){e.hp-=10;e.hit=16;fs.score+=120}if(fs.spawn<=0){let l=Math.random()<.5,v=4.3+Math.min(5,fs.t/400);rocks.push({x:l?-30:990,y:260+Math.random()*190,v:l?v:-v,r:12+Math.random()*12});fs.spawn=Math.max(25,68-fs.t/35)}rocks.forEach(r=>r.x+=r.v*dt);rocks=rocks.filter(r=>{if(overlap({x:r.x-r.r,y:r.y-r.r,w:r.r*2,h:r.r*2},{x:p.x,y:p.y,w:38,h:62})){if(p.inv<=0){p.hp-=12;p.inv=40}return false}return r.x>-70&&r.x<1030});if(Math.abs(p.x-e.x)<54&&p.y>365&&p.inv<=0&&Math.floor(fs.t)%75<2){p.hp-=8;p.inv=34}fs.score+=dt*1.4;$("#fightScore").textContent=`점수 ${Math.floor(fs.score)}`;if(p.hp<=0||e.hp<=0){fs.on=false;$("#fightTitle").textContent=e.hp<=0?`승리! ${Math.floor(fs.score)}점`:`다시 도전! ${Math.floor(fs.score)}점`;$("#fightStart").textContent="다시 시작";$("#fightCover").hidden=false}}
function drawFight(c=FC){let x=c.getContext("2d"),sx=c.width/960,sy=c.height/540;x.save();x.scale(sx,sy);drawExcelGrid(x,960,540);x.fillStyle="#e2f0d9";x.fillRect(0,482,960,58);x.strokeStyle="#217346";x.lineWidth=2;x.strokeRect(0,482,960,58);if(fs){let p=fs.p,e=fs.e;x.globalAlpha=p.inv>0&&Math.floor(p.inv/3)%2===0?.35:1;x.fillStyle="#217346";x.fillRect(p.x,p.y,38,62);x.globalAlpha=1;if(p.atk>0){x.fillStyle="#ffd966";x.fillRect(p.x+(p.x<e.x?38:-42),p.y+18,42,18)}x.fillStyle=e.hit>0?"#a9d18e":"#c65911";x.fillRect(e.x,410,48,72);rocks.forEach(r=>{x.beginPath();x.fillStyle="#bf9000";x.arc(r.x,r.y,r.r,0,Math.PI*2);x.fill()});x.fillStyle="#d9e2f3";x.fillRect(22,42,280,15);x.fillRect(658,42,280,15);x.fillStyle="#70ad47";x.fillRect(22,42,280*Math.max(0,p.hp)/100,15);x.fillStyle="#c65911";x.fillRect(658,42,280*Math.max(0,e.hp)/100,15);x.fillStyle="#44546a";x.font="12px Segoe UI";x.fillText("진행률",22,34);x.fillText("검토율",658,34)}x.restore()}
let prev=performance.now();function loop(now){let dt=Math.min(2,(now-prev)/16.67);prev=now;fightUpdate(dt);drawFight();if(mz.playing)$("#mazeTime").textContent=((now-mz.start)/1000).toFixed(1)+"초";if($("#mini").classList.contains("on")){if(miniGame==="maze"&&mz.cells.length)paintMaze($("#miniCanvas"));else drawFight($("#miniCanvas"))}requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener("keydown",e=>{if(e.key==="Escape"){$("#fake").classList.toggle("on");return}let mm={ArrowUp:"up",w:"up",W:"up",ArrowDown:"down",s:"down",S:"down",ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right"};if((active==="maze"||($("#mini").classList.contains("on")&&miniGame==="maze"))&&mm[e.key]){e.preventDefault();mazeMove(mm[e.key])}let fm={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"jump",w:"jump",W:"jump"," ":"attack",j:"attack",J:"attack",Shift:"dodge",k:"dodge",K:"dodge"};if((active==="fight"||($("#mini").classList.contains("on")&&miniGame==="fight"))&&fm[e.key]){e.preventDefault();fact(fm[e.key],true)}});addEventListener("keyup",e=>{let fm={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"jump",w:"jump",W:"jump"," ":"attack",j:"attack",J:"attack",Shift:"dodge",k:"dodge",K:"dodge"};if(fm[e.key])fact(fm[e.key],false)});
$("#installBtn").onclick=async()=>{if(matchMedia("(display-mode: standalone)").matches)return alert("이미 앱으로 실행 중입니다.");if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else alert(/iPhone|iPad/.test(navigator.userAgent)?"Safari 공유 버튼 → 홈 화면에 추가를 선택하세요.":"브라우저 메뉴에서 ‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택하세요.")};$("#miniBtn").onclick=()=>{let game=active==="fight"?"fight":"maze",w=390,h=315,left=Math.max(0,(screen.availLeft||0)+screen.availWidth-w-10),top=Math.max(0,(screen.availTop||0)+screen.availHeight-h-10),pop=window.open(`${location.pathname}?popup=1&game=${game}`,"mogeom_popup",`popup=yes,width=${w},height=${h},left=${left},top=${top},resizable=yes,scrollbars=no`);if(pop)pop.focus();else alert("팝업이 차단되었습니다. 주소창 오른쪽의 팝업 허용을 눌러주세요.")};$("#miniClose").onclick=()=>popupMode?window.close():$("#mini").classList.remove("on");$("#miniSwitch").onclick=()=>{miniGame=miniGame==="maze"?"fight":"maze";$("#miniTitle").textContent=miniGame==="maze"?"미로 탈출":"회피권";if(miniGame==="fight"&&!fs)startFight();if(miniGame==="maze"&&!mz.cells.length)makeMaze(1)};$("#panic").onclick=()=>$("#fake").classList.add("on");if(popupMode){document.body.classList.add("popupMode");$("#mini").classList.add("on");$("#miniTitle").textContent=miniGame==="maze"?"미로 탈출":"회피권";document.title="작은 게임";try{window.resizeTo(390,315);window.moveTo(Math.max(0,(screen.availLeft||0)+screen.availWidth-400),Math.max(0,(screen.availTop||0)+screen.availHeight-325))}catch(e){}if(miniGame==="maze")makeMaze(1);else startFight()}
const SAVE_KEY="workbookArcadeSaveV1";let saveData={mazeLevel:1,rankings:[]};try{saveData={...saveData,...JSON.parse(localStorage.getItem(SAVE_KEY)||"{}")}}catch(e){}mz.level=Math.max(1,saveData.mazeLevel||1);
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(saveData));let s=$("#saveStatus");if(s){s.textContent="자동 저장 완료 · "+new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"});clearTimeout(persist.t);persist.t=setTimeout(()=>s.textContent="자동 저장 사용 중",1800)}}
function addRank(game,score,text){saveData.rankings.push({game,score,text,date:new Date().toLocaleDateString("ko-KR")});saveData.rankings.sort((a,b)=>b.score-a.score);saveData.rankings=saveData.rankings.slice(0,5);persist();renderRanks()}
function renderRanks(){let rows=$("#rankRows");if(!rows)return;rows.innerHTML=saveData.rankings.length?saveData.rankings.map((r,i)=>`<tr><td>${i+1}</td><td>${r.game}</td><td>${r.text}</td><td>${r.date}</td></tr>`).join(""):`<tr><td colspan="4">아직 저장된 기록이 없습니다.</td></tr>`}renderRanks();
let baseMazeMove=mazeMove;mazeMove=function(d){let level=mz.level,started=mz.start;baseMazeMove(d);if(mz.level>level){let sec=(performance.now()-started)/1000,score=Math.max(1,Math.round(level*1000-sec*10));saveData.mazeLevel=mz.level;addRank("경로 검토",score,`LEVEL ${level} · ${sec.toFixed(1)}초`)}};
let baseFightUpdate=fightUpdate;fightUpdate=function(dt){let was=fs&&fs.on;baseFightUpdate(dt);if(was&&fs&&!fs.on)addRank("반응 검사",Math.floor(fs.score),`${Math.floor(fs.score)}점`)};
let sudokuRecorded="",baseCheckSudoku=checkSudoku;checkSudoku=function(){baseCheckSudoku();if($("#sudokuMsg").textContent.startsWith("정답")){let id=sudokuSolution.join("");if(id!==sudokuRecorded){sudokuRecorded=id;let score={easy:300,medium:600,hard:900}[sudokuDifficulty];addRank("수치 검산",score,`${{easy:"초급",medium:"중급",hard:"고급"}[sudokuDifficulty]} 완료`)}}};$("#sudokuCheck").onclick=checkSudoku;
let photoImage=null,photoDiffs=[],photoFound=new Set(),photoStarted=0;const PLC=$("#photoLeft"),PRC=$("#photoRight");
function drawPhotoCanvas(c,side){let x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);if(!photoImage){x.fillStyle="#eef2ef";x.fillRect(0,0,c.width,c.height);x.fillStyle="#65736a";x.font="12px Segoe UI";x.textAlign="center";x.fillText("사진을 선택하세요",c.width/2,c.height/2);return}let scale=Math.min(c.width/photoImage.width,c.height/photoImage.height),w=photoImage.width*scale,h=photoImage.height*scale,ox=(c.width-w)/2,oy=(c.height-h)/2;x.drawImage(photoImage,ox,oy,w,h);if(side)photoDiffs.forEach((d,i)=>{let sx=c.width/480,sy=c.height/320,dx=d.x*sx,dy=d.y*sy,rx=d.r*sx,ry=d.r*sy;x.save();x.beginPath();x.ellipse(dx,dy,rx,ry,0,0,Math.PI*2);x.clip();if(d.type==="shift")x.drawImage(photoImage,ox+d.shift*sx,oy-d.shift*sy,w,h);else if(d.type==="tint"){x.fillStyle=d.color;x.fillRect(dx-rx,dy-ry,rx*2,ry*2)}else{x.filter="grayscale(1) contrast(1.35)";x.drawImage(photoImage,ox,oy,w,h);x.filter="none"}x.restore();if(photoFound.has(i)){x.beginPath();x.ellipse(dx,dy,rx+3,ry+3,0,0,Math.PI*2);x.strokeStyle="#d71920";x.lineWidth=Math.max(2,c.width/160);x.stroke()}})}
function drawPhoto(){[[PLC,0],[PRC,1],[$("#miniPhotoLeft"),0],[$("#miniPhotoRight"),1]].forEach(([c,s])=>c&&drawPhotoCanvas(c,s))}
function makePhotoPuzzle(){if(!photoImage)return;photoFound.clear();photoStarted=performance.now();photoDiffs=[];let types=shuffled(["shift","tint","mono"]);while(photoDiffs.length<3){let d={x:65+Math.random()*350,y:55+Math.random()*210,r:20+Math.random()*8,type:types[photoDiffs.length],shift:10+Math.random()*8,color:["#ffffffaa","#21734699","#ffd966aa"][photoDiffs.length]};if(photoDiffs.every(q=>Math.hypot(q.x-d.x,q.y-d.y)>q.r+d.r+28))photoDiffs.push(d)}$("#photoScore").textContent="0 / 3";$("#photoMsg").textContent="오른쪽 사진에서 겹치지 않는 차이점 3개를 찾으세요.";drawPhoto()}
function loadPhoto(file){if(!file)return;let img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{photoImage=img;makePhotoPuzzle();URL.revokeObjectURL(url)};img.src=url}
$("#photoInput").onchange=e=>loadPhoto(e.target.files[0]);$("#miniPhotoInput").onchange=e=>loadPhoto(e.target.files[0]);$("#photoFolder").onchange=e=>{let files=[...e.target.files].filter(f=>f.type.startsWith("image/"));if(files.length)loadPhoto(files[Math.floor(Math.random()*files.length)]);else $("#photoMsg").textContent="선택한 폴더에 사진이 없습니다."};$("#photoNew").onclick=makePhotoPuzzle;
function photoClick(c,e){if(!photoImage)return;let r=c.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width,y=(e.clientY-r.top)*320/r.height;photoDiffs.forEach((d,i)=>{if(!photoFound.has(i)&&Math.hypot(x-d.x,y-d.y)<d.r+13)photoFound.add(i)});$("#photoScore").textContent=`${photoFound.size} / 3`;drawPhoto();if(photoFound.size===3){let sec=(performance.now()-photoStarted)/1000,score=Math.max(1,Math.round(1000-sec*10));$("#photoMsg").textContent=`검수 완료 · ${sec.toFixed(1)}초`;addRank("이미지 검수",score,`${sec.toFixed(1)}초`)}}
PRC.onclick=e=>photoClick(PRC,e);$("#miniPhotoRight").onclick=e=>photoClick($("#miniPhotoRight"),e);drawPhoto();
function showMiniGame(){let names={maze:"경로 검토",fight:"반응 검사",sudoku:"수치 검산",photo:"이미지 비교"};$("#miniTitle").textContent=names[miniGame];let sudoku=miniGame==="sudoku",photo=miniGame==="photo";$("#miniCanvas").style.display=sudoku||photo?"none":"block";$("#miniSudoku").classList.toggle("on",sudoku);$("#miniPhoto").classList.toggle("on",photo);if(sudoku)renderMiniSudoku();else if(photo)drawPhoto();else if(miniGame==="fight"&&!fs)startFight();else if(miniGame==="maze"&&!mz.cells.length)makeMaze(mz.level)}
$("#miniSwitch").onclick=()=>{let games=["maze","fight","sudoku","photo"];miniGame=games[(games.indexOf(miniGame)+1)%games.length];showMiniGame()};
$("#miniBtn").onclick=()=>{let game=["fight","maze","sudoku","photo"].includes(active)?active:"maze",w=390,h=315,left=Math.max(0,(screen.availLeft||0)+screen.availWidth-w-10),top=Math.max(0,(screen.availTop||0)+screen.availHeight-h-10),pop=window.open(`${location.pathname}?popup=1&game=${game}`,"work_status_popup",`popup=yes,width=${w},height=${h},left=${left},top=${top},resizable=yes,scrollbars=no`);if(pop)pop.focus();else{miniGame=game;$("#mini").classList.add("on");showMiniGame()}};
$("#installBtn").onclick=async()=>{let html=await fetch(location.pathname,{cache:"no-store"}).then(r=>r.text()),url=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="work-status-MGAM.html";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
if(popupMode){document.title="업무 현황 사이트_MGAM";showMiniGame()}

